server.port=8081

spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DATADASE_USERNAME}
spring.datasource.password=${DATADASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Actuator
management.endpoints.web.exposure.include=mappings,beans,caches,env,metrics,shutdown,auditevents,threaddump
management.endpoint.env.show-values=always

# File settings
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

#Log settings from Logback in SpringBoot
logging.level.root=INFO
logging.file.name=logs/spring-boot-log.log

jwt.expiration=${JWT_EXPIRATION:1}
jwt.secret=${JWT_SECRET}