server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/todo39
spring.datasource.username=user39
spring.datasource.password=${DATADASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Actuator
management.endpoints.web.exposure.include=mappings,beans,caches,env,metrics,shutdown,auditevents,threaddump
management.endpoint.env.show-values=always
management.endpoint.shutdown.access=unrestricted

# File settings
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

#Log settings from Logback in SpringBoot
logging.level.root=INFO
logging.file.name=logs/spring-boot-log.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

jwt.expiration=${jwt.expiration:5}
jwt.secret=${jwt.secret}