spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/WEB-INF/views/

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/todo39
spring.datasource.username=user39
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver